// <auto-generated />
using System;
using Farm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Farm.Data.Migrations
{
    [DbContext(typeof(FarmContext))]
    [Migration("20201125064637_CreateBd")]
    partial class CreateBd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Farm.Data.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMultyHarvest")
                        .HasColumnType("bit");

                    b.Property<int?>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("NameAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProduktAnimalProduktOfAnimalId")
                        .HasColumnType("int");

                    b.Property<int?>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("TimeBetweenHarvests")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("MarketId");

                    b.HasIndex("ProduktAnimalProduktOfAnimalId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Farm.Data.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AriaOfBuilding")
                        .HasColumnType("int");

                    b.Property<int>("ContentAnimals")
                        .HasColumnType("int");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("NameBuilding")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId");

                    b.HasIndex("FarmId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Farm.Data.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<int?>("MarketForFarmMarketId")
                        .HasColumnType("int");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NameFarm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RawMaterialOnFarmRawMaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("StockInCountryStockId")
                        .HasColumnType("int");

                    b.HasKey("FarmId");

                    b.HasIndex("MarketForFarmMarketId");

                    b.HasIndex("RawMaterialOnFarmRawMaterialId");

                    b.HasIndex("StockInCountryStockId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("Farm.Data.GardenBed", b =>
                {
                    b.Property<int>("GardenBedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("Square")
                        .HasColumnType("int");

                    b.HasKey("GardenBedId");

                    b.HasIndex("FarmId");

                    b.ToTable("GardenBeds");
                });

            modelBuilder.Entity("Farm.Data.Market", b =>
                {
                    b.Property<int>("MarketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("MarketId");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("Farm.Data.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AriaOfSeat")
                        .HasColumnType("int");

                    b.Property<int?>("GardenBedId")
                        .HasColumnType("int");

                    b.Property<int>("Harvest")
                        .HasColumnType("int");

                    b.Property<bool>("IsMultyHarvest")
                        .HasColumnType("bit");

                    b.Property<string>("NamePlant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonGather")
                        .HasColumnType("int");

                    b.Property<int>("SeasonSeat")
                        .HasColumnType("int");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.HasKey("PlantId");

                    b.HasIndex("GardenBedId");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("StockId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Farm.Data.ProduktOfAnimal", b =>
                {
                    b.Property<int>("ProduktOfAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<string>("NameProduktOfAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.HasKey("ProduktOfAnimalId");

                    b.HasIndex("StockId");

                    b.ToTable("ProduktsOfAnimal");
                });

            modelBuilder.Entity("Farm.Data.RawMaterial", b =>
                {
                    b.Property<int>("RawMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("RawMaterialId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("Farm.Data.Seed", b =>
                {
                    b.Property<int>("SeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("PlantsSeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeasonSeat")
                        .HasColumnType("int");

                    b.HasKey("SeedId");

                    b.HasIndex("MarketId");

                    b.ToTable("Seeds");
                });

            modelBuilder.Entity("Farm.Data.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("VolumeStock")
                        .HasColumnType("int");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Farm.Data.Animal", b =>
                {
                    b.HasOne("Farm.Data.Building", null)
                        .WithMany("AnimalsOnBild")
                        .HasForeignKey("BuildingId");

                    b.HasOne("Farm.Data.Market", null)
                        .WithMany("AnimalsToBuy")
                        .HasForeignKey("MarketId");

                    b.HasOne("Farm.Data.ProduktOfAnimal", "ProduktAnimal")
                        .WithMany()
                        .HasForeignKey("ProduktAnimalProduktOfAnimalId");

                    b.HasOne("Farm.Data.RawMaterial", null)
                        .WithMany("AnimalsFree")
                        .HasForeignKey("RawMaterialId");

                    b.Navigation("ProduktAnimal");
                });

            modelBuilder.Entity("Farm.Data.Building", b =>
                {
                    b.HasOne("Farm.Data.Farm", null)
                        .WithMany("BuildingFarm")
                        .HasForeignKey("FarmId");
                });

            modelBuilder.Entity("Farm.Data.Farm", b =>
                {
                    b.HasOne("Farm.Data.Market", "MarketForFarm")
                        .WithMany()
                        .HasForeignKey("MarketForFarmMarketId");

                    b.HasOne("Farm.Data.RawMaterial", "RawMaterialOnFarm")
                        .WithMany()
                        .HasForeignKey("RawMaterialOnFarmRawMaterialId");

                    b.HasOne("Farm.Data.Stock", "StockInCountry")
                        .WithMany()
                        .HasForeignKey("StockInCountryStockId");

                    b.Navigation("MarketForFarm");

                    b.Navigation("RawMaterialOnFarm");

                    b.Navigation("StockInCountry");
                });

            modelBuilder.Entity("Farm.Data.GardenBed", b =>
                {
                    b.HasOne("Farm.Data.Farm", null)
                        .WithMany("GardenBedFarm")
                        .HasForeignKey("FarmId");
                });

            modelBuilder.Entity("Farm.Data.Plant", b =>
                {
                    b.HasOne("Farm.Data.GardenBed", null)
                        .WithMany("PlantsBed")
                        .HasForeignKey("GardenBedId");

                    b.HasOne("Farm.Data.RawMaterial", null)
                        .WithMany("PlantsFree")
                        .HasForeignKey("RawMaterialId");

                    b.HasOne("Farm.Data.Stock", null)
                        .WithMany("Plants")
                        .HasForeignKey("StockId");
                });

            modelBuilder.Entity("Farm.Data.ProduktOfAnimal", b =>
                {
                    b.HasOne("Farm.Data.Stock", null)
                        .WithMany("ProduktsOfAnimal")
                        .HasForeignKey("StockId");
                });

            modelBuilder.Entity("Farm.Data.Seed", b =>
                {
                    b.HasOne("Farm.Data.Market", null)
                        .WithMany("SeedsToBuy")
                        .HasForeignKey("MarketId");
                });

            modelBuilder.Entity("Farm.Data.Building", b =>
                {
                    b.Navigation("AnimalsOnBild");
                });

            modelBuilder.Entity("Farm.Data.Farm", b =>
                {
                    b.Navigation("BuildingFarm");

                    b.Navigation("GardenBedFarm");
                });

            modelBuilder.Entity("Farm.Data.GardenBed", b =>
                {
                    b.Navigation("PlantsBed");
                });

            modelBuilder.Entity("Farm.Data.Market", b =>
                {
                    b.Navigation("AnimalsToBuy");

                    b.Navigation("SeedsToBuy");
                });

            modelBuilder.Entity("Farm.Data.RawMaterial", b =>
                {
                    b.Navigation("AnimalsFree");

                    b.Navigation("PlantsFree");
                });

            modelBuilder.Entity("Farm.Data.Stock", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("ProduktsOfAnimal");
                });
#pragma warning restore 612, 618
        }
    }
}
